#define TIMG0_BASE 0x3FF5F000
#define TIMG1_BASE 0x3FF60000

#define SUBT0_BASE 0
#define SUBT1_BASE 0x24

#define TIMGX_TNLO_REG 0x4
#define TIMGX_TNHI_REG 0x8
#define TIMGX_TNUPDATE_REG 0xC
#define TIMGX_TNLOAD_REG 0x20


#define G0T0

#ifdef G0T0
#define LO_REG (TIMG0_BASE + SUBT0_BASE + TIMGX_TNLO_REG)
#define HI_REG (TIMG0_BASE + SUBT0_BASE + TIMGX_TNHI_REG)
#define UPDATE_REG (TIMG0_BASE + SUBT0_BASE + TIMGX_TNUPDATE_REG)
#define LOAD_REG (TIMG0_BASE + SUBT0_BASE + TIMGX_TNLOAD_REG)
#endif

#ifdef G0T1
#define LO_REG (TIMG0_BASE + SUBT1_BASE + TIMGX_TNLO_REG)
#define HI_REG (TIMG0_BASE + SUBT1_BASE + TIMGX_TNHI_REG)
#define UPDATE_REG (TIMG0_BASE + SUBT1_BASE + TIMGX_TNUPDATE_REG)
#define LOAD_REG (TIMG0_BASE + SUBT1_BASE + TIMGX_TNLOAD_REG)
#endif

#ifdef G1T0
#define LO_REG (TIMG1_BASE + SUBT0_BASE + TIMGX_TNLO_REG)
#define HI_REG (TIMG1_BASE + SUBT0_BASE + TIMGX_TNHI_REG)
#define UPDATE_REG (TIMG1_BASE + SUBT0_BASE + TIMGX_TNUPDATE_REG)
#define LOAD_REG (TIMG1_BASE + SUBT0_BASE + TIMGX_TNLOAD_REG)
#endif

#ifdef G1T1
#define LO_REG (TIMG1_BASE + SUBT1_BASE + TIMGX_TNLO_REG)
#define HI_REG (TIMG1_BASE + SUBT1_BASE + TIMGX_TNHI_REG)
#define UPDATE_REG (TIMG1_BASE + SUBT1_BASE + TIMGX_TNUPDATE_REG)
#define LOAD_REG (TIMG1_BASE + SUBT1_BASE + TIMGX_TNLOAD_REG)
#endif

class 